server:
  port: ${PORT:8080}

security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

spring:
  application:
    name: dscatalog

  profiles:
    active: ${APP_PROFILE:dev}

  jpa:
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: test

  # --- DATASOURCE (H2) ---
  datasource:
    url: jdbc:h2:mem:testdb
    username: dev
    password:
    driver-class-name: org.h2.Driver

  # --- H2 CONSOLE WEB ---
  h2:
    console:
      enabled: true
      path: /h2-console

  # --- JPA / HIBERNATE ---
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop
    show-sql: true # Log SQL queries to the console
    init:
      mode: always
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none # "none", "validate", "update", "create" ou "create-drop"
    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
      hibernate:
#        hbm2ddl:
#          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5433/ds_catalog
    username: postgres
    password: ${DB_PASSWORD:123456}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# src/main/resources/application-prod.yml
logging:
  level:
    root: INFO
