server:
  port: ${PORT:8080}

security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

spring:
  application:
    name: dscatalog

  profiles:
    active: ${APP_PROFILE:test}

  jpa:
    open-in-view: false

  mail:
    host: ${APP_HOST}
    username: ${APP_EMAIL}
    password: ${APP_PASSWORD}
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

email:
  password-recover:
    token:
      minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:30}
    uri: ${PASSWORD_RECOVER_URI:http://localhost:5173/recover-password/}

  remetente: "✉️ Dscatalog Application"
  to: samuelb2f@outlook.com
  title: Recuperação de senha
  message: "Acesse o link para definir uma nova senha:"
  link: http://localhost:5173/recover-password/


---
#=================
# TEST ENVIRONMENT
#=================
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: dev
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

---
#=================
# DEV ENVIRONMENT
#=================
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update} # create update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    properties:
      hibernate:
        hbm2ddl:
          delimiter: ;

  datasource:
    url: jdbc:postgresql://localhost:5433/dscatalog
    username: postgres
    password: 1234567

  sql:
    init:
      mode: ${SQL_INIT_MODE:never} # never always

---
#=================
# PROD ENVIRONMENT
#=================
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO